name: Frontend Continuous Deployment

on:
  push:
    branches:
      - main
    paths:
      - "starter/frontend/**"
  workflow_dispatch:

jobs:
  lint:
    name: Lint Frontend
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: starter/frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "18.14"

      - name: Install dependencies
        run: npm ci

      - name: Run lint
        run: npm run lint

  test:
    name: Test Frontend
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: starter/frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "18.14"

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run test
        env:
          CI: true

  build:
    name: Build Frontend
    runs-on: ubuntu-latest

    needs:
      - lint
      - test

    defaults:
      run:
        working-directory: starter/frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Login to Amazon ECR Public
        run: |
          aws ecr-public get-login-password --region us-east-1 | \
            docker login --username AWS --password-stdin public.ecr.aws

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build \
            --build-arg REACT_APP_MOVIE_API_URL=http://afbc121f39136462ba474fd33ce8bee0-1786226472.us-east-1.elb.amazonaws.com \
            --tag $ECR_REGISTRY/frontend:$IMAGE_TAG \
            .

      - name: Push Docker image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker push $ECR_REGISTRY/frontend:$IMAGE_TAG

      - name: Update kubeconfig
        run: aws eks update-kubeconfig --region us-east-1 --name cluster

      - name: Deploy to EKS
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          cd k8s
          kustomize edit set image frontend=$ECR_REGISTRY/frontend:$IMAGE_TAG
          kubectl apply -k .

      - name: Verify Kubernetes deployment
        run: |
          kubectl rollout status deployment/frontend --timeout=180s
          echo "----- Logging - kubectl get all ---- "
          kubectl get all
          echo "----- Logging - kubectl describe deploy ----- "
          kubectl describe deploy frontend

      - name: Verify Frontend ECR image
        run: |
          echo "----- Logging - Frontend ECR Image Details ----- "
          AWS_PAGER="" aws ecr describe-images \
            --repository-name frontend \
            --region us-east-1 \
            --query 'sort_by(imageDetails,&imagePushedAt)[-1].{Tags:imageTags,Digest:imageDigest,PushedAt:imagePushedAt}' \
            --output table
